[project]
name = "brl-parliament-mcp"
version = "0.1.0"
description = "MCP Server for Brazilian Parliament"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.13.1",
    "pymupdf>=1.26.4",
]
